FROM xsteadfastx/tox-python

RUN set -ex \
 && pip install \
        pex \
        pipenv \
 && pip3.6 install wheel \
 && pip3.5 install wheel \
 && pip3.4 install wheel

WORKDIR /data

CMD tools/build-pex.sh
